<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>promise</title>
	<link rel="stylesheet" href="../css/normalize.css">
	<link rel="stylesheet" href="../css/styles/default.css">
	<link rel="stylesheet" href="../css/sidebar.css">
	<script src="../js/jquery-3.2.1-compressed.js"></script>
	<script src="../js/highlight.pack.js"></script>
	<script src="../js/sidebar.js"></script>
</head>
<body>
	<aside id="sidebar">
		<section id="catalog">
			<img id="hideCatalog" src="../images/catalog.png" alt="加载失败">
			目录
		</section>
	</aside>
	<div id="showCatalog">
		<img src="../images/arrow.png">
	</div>
	<article id="container">
		<hgroup>
			<h1 id="title">Promise</h1>
		</hgroup>
		<section>
			<h2>定义</h2>
			<p>
				Promise 是 ES6 新增的构造函数，用于更方便地实现异步编程。
				<pre><code class="javascript">
// 创建一个 Promise 实例，传入执行函数
// 执行函数的参数为 resolve 函数和 reject 函数
var 实例 = new Promise(function(resolve, reject) {
	... // 一堆代码
	if (...) { // 如果达到某个条件，就执行 resolve 函数
		resolve(value);
	}
	if (...) { // 如果达到某个条件，就执行 reject 函数
		reject(value);
	}
});

// 执行异步任务，reject 函数是可选的
// 设置 resolve 函数和 reject 函数的执行内容
实例对象.then(function(value){
	// resolve 函数
}, function(value){
	// reject 函数
});
				</code></pre>
				通俗地将，我们在<span class="different"> new Promise(function(resolve, reject) { //... }) </span>中写入代码，使用<span class="different"> resolve(data) </span>传递代码执行成功后得到的数据，使用<span class="different"> reject(error) </span>传递代码执行失败后得到的错误信息。然后使用<span class="different"> 实例对象.then(function(data) {}) </span>拿到成功时的数据，使用<span class="different"> .catch(function(error) {}) </span>拿到失败时的错误信息。
			</p>
		</section>
		<section>
			<h2>使用</h2>
			<p>
				<h3>概念</h3>
				promise 的实例对象有三种状态：<span class="definition"> pending、fulfilled、rejected </span>。
				<ul>
					<li>pending：执行中状态，new Promise 后执行一堆代码的整个过程</li>
					<li>fulfilled：完成状态，执行了 reslove 函数</li>
					<li>rejected：出错状态，执行了 reject 函数或执行一堆代码时出错</li>
					<li>fulfill：将 pending 状态变成 fulfilled 状态（settled）</li>
					<li>reject：将 pending 状态变成 rejected 状态（settled）</li>
					<li>return：resolve 函数或 reject 函数执行完后必然返回一个 promise 对象，用于链式调用</li>
				</ul>
				<figure>
					<img src="../images/promise_life.png">
				</figure>
				<h3>执行过程</h3>
				<pre><code class="javascript">
var promise = new Promise(function(resolve, reject) {
	resolve('执行 resolve 里的代码');
	reject('执行 reject 里的代码');
	console.log('执行 new Promise 里的代码');
});
promise.then(function(value) {
	console.log(value);
}, function(value) {
	console.log(value);
});
console.log('执行 window 里的代码');
				</code></pre>
				<figure>
					<img src="../images/promise_demo1.jpg">
				</figure>
				其上例子执行过程为：
				<ol>
					<li>创建 promise 实例，传入执行函数（executor）</li>
					<li>执行 executor 里的代码，控制台输出<span class="definition"> 执行 new Promise 里的代码 </span></li>
					<li>执行 executor 过程中先执行 reslove 函数，所以异步调用 resolve 函数，传入形参<span class="definition"> 执行 resolve 里的代码 </span></li>
					<li>执行 promise.then 对 resolve 函数和 reject 函数的内容进行设置</li>
					<li>控制台输出<span class="definition"> 执行 window 里的代码 </span></li>
					<li>异步执行（终于） resolve 函数，控制台输出<span class="definition"> 执行 resolve 里的代码 </span></li>
				</ol>
				<h3>传统回调</h3>
				<p>
					传统的回调方式是将函数传入另一个函数里面，在该函数内某个位置执行。
					<pre><code class="javascript">
function a (fun) {
	// a 的代码
	fun();
}
function b () {
	// b 的代码
}
a(b);
					</code></pre>
					而 promise 是先执行 new Promise 时传入的函数的代码，等到调用并传入 resolve 或 reject 回调函数时，才会执行这些回调。
					<pre><code class="javascript">
function a () { // a 的代码 }
function b () { // b 的代码 }
var p = new Promise(function (resolve, reject) {
	a(); // 优先执行 a 的代码
	resolve(); // 调用回调函数 resolve
});
p.then(b); // 传入 b 作为回调函数 resolve
					</code></pre>
				</p>
				<h3>触发回调</h3>
				resolve 和 reject 称为回调函数，要触发回调，需要满足：
				<ol>
					<li>在 new Promise 中执行了 resolve 或 reject 函数或报错</li>
					<li>执行 resolve 或 reject 函数时传入的参数非 pending 状态的 promise 对象</li>
					<li>promise 对象执行了 then 或者 catch 方法</li>
				</ol>
				<h4>需要 promise 对象的状态变更为 fulfill 或 reject 时才会去触发回调</h4>
				<pre><code class="javascript">
var p1 = new Promise(function(resolve, reject) {
	setTimeout(resolve, 3000);
});
p1.then(function() {
	console.log('resolve 了');
});
				</code></pre>
				<figure>
					<img src="../images/promise_resolve_1.gif" alt="">
					<figcaption>3s 后才执行 resolve（将状态变更为 fulfill），此时才触发回调</figcaption>
				</figure>
				<h4>调用 resolve 或 reject 回调函数时，其形参是非 pending 对象</h4>
				<pre><code class="javascript">
var p1 = new Promise(function(resolve, reject){
	setTimeout(resolve, 3000);
});
var p2 = new Promise(function(resolve, reject){
	resolve(p1);
});
p2.then(function(value){
	console.log(value);
	console.log('p2 的 resolve 被调用了');
});
				</code></pre>
				<figure>
					<img src="../images/promise_resolve.gif">
					<figcaption>3s 后控制台才输出内容</figcaption>
				</figure>
				<h4>使用了 then 或 catch，即传入了回调函数</h4>
				<pre><code class="javascript">
var p1 = new Promise(function(resolve, reject) {
	resolve();
});
setTimeout(function () {
	p1.then(function () {
		console.log('you have a resolve');
	});
}, 3000);
				</code></pre>
				<figure>
					<img src="../images/promise_resolve_2.gif" alt="">
					<figure>3s 后才传入回调函数</figure>
				</figure>
				<h3>链式调用</h3>
				promise.then 返回一个新的 promise 对象，所以可以进行链式调用。
				<pre><code class="javascript">
var promise = new Promise(function(resolve, reject) {
	resolve('hello promise');
});
promise.then(function(value) {
	console.log(value);
}).then(function(value) {
	console.log(value);
});
				</code></pre>
				<figure>
					<img src="../images/promise_demo2.jpg">
				</figure>
				可以看到，第二个 then 执行的 resolve 输出了 undefined ，这是因为以上代码等价于
				<pre><code class="javascript">
var promise = new Promise(function(resolve, reject) {
	resolve('hello promise');
});
promise.then(function(value) {
	console.log(value);
	<div class="strong">
return new Promise(function(resolve, reject) {
	resolve();
});
	</div>
}).then(function(value) {
	console.log(value);
});
				</code></pre>
				第一个 resolve 函数<b>自动</b>返回了个新的 promise 对象（没写 return 时），该 promise 对象又执行了 reslove 函数，传入的参数为空，因此第二个 resolve 函数输出的 value 为 undefined。正确的值传递应该是手写 return：
				<pre><code class="javascript">
var promise = new Promise(function(resolve, reject) {
	resolve('hello promise');
});
promise.then(function(value) {
	console.log(value);
	<div class="strong">
return new Promise(function(resolve, reject) {
	resolve(value);
});
	</div>
}).then(function(value) {
	console.log(value);
});
				</code></pre>
				当你只是想返回一个值给下一个 then 用，不必创建 Promise 对象再调用 resolve 回调函数进行传数据，可以直接将该数据返回，效果是一样的。
				<pre><code class="javascript">
promise.then(function(value) {
	console.log(value);
	<div class="strong">
return value;
	</div>
}).then(function(value) {
	console.log(value);
})
				</code></pre>
				<figure>
					<img src="../images/promise_demo3.jpg">
				</figure>
				前一个 then 返回的 promise 对象影响后一个 then 的 resolve 回调，只有前一个 then 返回的 primise 对象执行了 resolve 函数，后一个 then 才执行，<b>保证了链式调用的顺序</b>。
				<pre><code class="javascript">
var promise = new Promise(function(resolve, reject){
	resolve();
});
promise.then(function(){
	console.log('第一个 then');
	return new Promise(function(resolve, reject){
		setTimeout(resolve, 1000);
	});
}).then(function(){
	console.log('第二个 then');
	return new Promise(function(resolve, reject){
		setTimeout(resolve, 1000);
	});
}).then(function(){
	console.log('第三个 then');
});
				</code></pre>
				<figure>
					<img src="../images/promise_chain.gif">
				</figure>
			</p>
		</section>
		<section>
			<h2>catch</h2>
			<p>
				<span class="definition"> catch(function(value){}) </span> 相当于<span class="definition"> then(null, function(value){}) </span>，catch 用于捕获前面所有 promise 对象抛出的错误（执行 reject 函数相当于抛出一个错误）。
				<pre><code class="javascript">
/* 方法一 */
promise.then(function(value){
	// ...
}, function(value){
	// ...
});

/* 方法二 */
promise.then(function(value){
	// ...
}).catch(function(value){
	// ...
});
				</code></pre>
				以上写法功能类似，但不等价，方法二可以捕获 new Promise 内执行的错误，同时也可以捕获到 resolve（then）执行的错误。
				<pre><code class="javascript">
var promise = new Promise(function(resolve, reject){
	resolve();
});
/* 方法一 */
promise.then(function(value){
	console.log('执行了 resolve');
	asdasd // 一段错误代码
}, function(value){
	console.log('执行了 reject');
});

/* 方法二 */
promise.then(function(value){
	console.log('执行了 resolve');
	asdasd // 一段错误代码
}).catch(function(value){
	console.log('执行了 catch');
});
				</code></pre>
				<figure>
					<img src="../images/promise_way1.jpg">
					<figcaption>方法一</figcaption>
				</figure>
				<figure>
					<img src="../images/promise_way2.jpg">
					<figcaption>方法二</figcaption>
				</figure>
			</p>
		</section>
		<section>
			<h2>finally</h2>
			<p>
				finally 方法：无论结果如何都会触发其回调函数，并且没有回调函数没有传入的参数。
				<pre><code class="javascript">
promise.finally(function(){
	console.log('无论如何我都会被执行');
});
				</code></pre>
			</p>
		</section>
		<section>
			<h2>静态/工厂方法</h2>
			<p>
				<ul>
					<li>Promise.all([])</li>
					<li>Promise.race([])</li>
				</ul>
				两个方法都是传入一个数组，数组元素是 promise 实例，最终返回一个新的 promise 对象，新的 promise 对象的状态取决于传入的数组的元素的执行结果。
				<h3>all</h3>
				对于 all 方法来说
				<ul>
					<li>当传入的数组的所有 promise 对象都是 fulfilled 状态时，返回的对象才是 fulfilled 状态</li>
					<li>当传入的数组的任意一个 promise 对象是 rejected 状态时，返回的对象是 rejected 状态</li>
				</ul>
				<pre><code class="javascript">
var promise = Promise.all(
	[
		new Promise(function(resolve, reject){
			setTimeout(function(){
				console.log('我是第一个');
				resolve();
			}, 1000);
		}),
		new Promise(function(resolve, reject){
			setTimeout(function(){
				console.log('我是第二个');
				resolve();
			}, 2000);
		}),
		new Promise(function(resolve, reject){
			setTimeout(function(){
				console.log('我是第三个');
				resolve();
			}, 3000);
		})
	]);
promise.then(function(){
	console.log('所有 promise 对象 fulfilled');
}).catch(function(){
	console.log('存在 promise 对象 rejected');
});
				</code></pre>
				<figure>
					<img src="../images/promise_all.gif">
					<figcaption>3s 后控制台输出所有的 promise 对象都 fulfilled</figcaption>
				</figure>
				<h3>race</h3>
				对于 race 方法来说，返回的对象的状态取决于第一个有结果的 promise 对象。
				<pre><code class="javascript">
var promise = Promise.race(
	[
		new Promise(function(resolve, reject){
			setTimeout(function(){
				console.log('我是第一个');
				resolve();
			}, 1000);
		}),
		new Promise(function(resolve, reject){
			setTimeout(function(){
				console.log('我是第二个');
				resolve();
			}, 2000);
		}),
		new Promise(function(resolve, reject){
			setTimeout(function(){
				console.log('我是第三个');
				resolve();
			}, 3000);
		})
	]);
promise.then(function(){
	console.log('存在 promise 对象 fulfilled');
}).catch(function(){
	console.log('存在 promise 对象 rejected');
});
				</code></pre>
				<figure>
					<img src="../images/promise_race.gif">
					<figcaption>1s 后第一个 promise 对象 fulfilled</figcaption>
				</figure>
			</p>
		</section>
		<section class="refer">
			<h2>参考文献</h2>
			<p>
				<div>[1] MDN Promise <a href="https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise">https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise</a></div>
				<div>[2] 阮一峰 ECMAScript 6 入门 <a href="http://es6.ruanyifeng.com/#docs/promise">http://es6.ruanyifeng.com/#docs/promise</a></div>
			</p>
		</section>
	</article>
</body>
</html>